# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               不二
tagline:             '拿酒来，酒染我长袍'
description:         '<h1 style="color:white">wood</h1><br>product designer<a href="https://twitter.com/woood_lou" title=“Twitter” target="_blank">@木之</a>'
url:                 https://woodlou.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              wood
  url:               https://twitter.com/woood_lou
  email:             louyingxia1991@gmail.com

# Custom vars
version:             1.0.0
