# External gems
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# info
title: 不二
subtitle: "拿酒来，酒染我长袍"
email: yingxialou@gmail.com
name: Wood'blog
description: > 
  wood's blog. 你没有如期归来，而这正是离别的意义。

# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://louyingxia.com" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives: 
  enabled: 
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: wood

# Google analytics
ga_tracking_id: "UA-111257287-4"



# Category descriptions (for archive pages)
descriptions:
  - cat: design
    desc: "怕什么真理无穷，进一寸有一寸的欢喜 "

  - cat: life
    desc: "我来到这世上，是为了看太阳 "

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: 不二
    url: https://twitter.com/wood__me
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: 不二
    url: 
    desc: Friend me on Facebook
    share: true


  - name: LinkedIn
    icon: linkedin
    username: wood
    url: 
    desc: Connect with me on LinkedIn
    share: true

  - name: Google+
    icon: google-plus
    username: 
    url: 
    desc: Add me to your Circles
    share: true

  - name: YouTube
    icon: youtube
    username: 
    url: 
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: Yingxia_me
    url: https://www.instagram.com/yingxia_me/
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username: Yingxia
    url: https://www.pinterest.com/yingxialou/
    desc: Follow me on Pinterest
    share: true

  - name: SoundCloud
    icon: soundcloud
    username: 
    url: 
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username: woodellf
    url: http://woodellf.tumblr.com/
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username: 
    url: 
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username: 
    url: 
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username: 
    url: 
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username: 
    url: 
    desc: Follow me on Vine
    share: false

  - name: GitHub
    icon: GitHub
    username:  ---theme by bencentra---
    url: https://github.com/bencentra 
    desc: theme by bencentra
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    #os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    #os_rcs_type: "git"
    #os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
